plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ccop.usbcpowermonitor'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ccop.usbcpowermonitor.energyv6'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName '6.0.0-energy-history'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
