package com.ccop.usbcpowermonitor;

import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import java.util.*;

/** Full-screen Bridge configurator. It only models and validates energy flow; it never electrically connects batteries. */
public class BridgeWizardActivity extends Activity {
    private static final int BG=Color.rgb(6,11,15),PANEL=Color.rgb(14,25,34),LINE=Color.rgb(43,61,74),TEXT=Color.rgb(247,249,252),MUTED=Color.rgb(151,164,178),BLUE=Color.rgb(24,153,255),CYAN=Color.rgb(73,194,255),OK=Color.rgb(48,214,132),WARN=Color.rgb(255,196,71);
    private ProfileStore profiles;private BridgeStore bridges;private BridgeStore.Bridge bridge;private Spinner a,b,cable,source,mode;private EditText name;private TextView summary;
    private List<ProfileStore.Profile>bats=new ArrayList<>(),cables=new ArrayList<>(),sources=new ArrayList<>();
    @Override protected void onCreate(Bundle x){super.onCreate(x);getWindow().setStatusBarColor(Color.rgb(4,21,30));getWindow().setNavigationBarColor(BG);profiles=new ProfileStore(this);bridges=new BridgeStore(this);String id=getIntent().getStringExtra("bridgeId");bridge=id==null?null:find(id);if(bridge==null)bridge=new BridgeStore.Bridge();for(ProfileStore.Profile p:profiles.loadActiveInventory()){if(p.isEnergyStore())bats.add(p);if(p.isCable())cables.add(p);if(!p.isCable())sources.add(p);}setContentView(build());}
    private BridgeStore.Bridge find(String id){for(BridgeStore.Bridge q:bridges.load())if(q.id.equals(id))return q;return null;}
    private View build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(16),dp(18),dp(28));root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(dp(18),dp(16)+in.getSystemWindowInsetTop(),dp(18),dp(28)+in.getSystemWindowInsetBottom());return in;});sv.addView(root);root.addView(txt("Bridge konfigurieren",29,TEXT,true));root.addView(txt("QUELLE → KABEL → AKKU A / B → MODUS → ENERGIEPOOL",11,CYAN,true));LinearLayout help=card();help.addView(txt("Was ist eine Bridge?",18,TEXT,true));help.addView(txt("Eine Bridge ist in der App eine bestätigte Kombination von Ladequelle, Kabel und Akkus. Sie berechnet Energiepool, SOC und Laufzeit. Die App schaltet Akkus niemals elektrisch zusammen. Direkte Hardware-Verbindungen müssen vom Hersteller dafür vorgesehen sein.",12,MUTED,false));add(root,help);
        if(bats.size()<2){LinearLayout warn=card();warn.addView(txt("Noch nicht genug Akkuprofile",18,WARN,true));warn.addView(txt("Für eine Zwei-Akku-Bridge müssen zuerst zwei Powerbanks/externe Akkus mit Kapazität angelegt werden. Zurück zu Profile → Gerät per Foto/OCR erfassen.",13,MUTED,false));add(root,warn);Button back=primary("ZURÜCK ZU PROFILEN");back.setOnClickListener(v->finish());add(root,back);return sv;}
        LinearLayout form=card();name=input(bridge.name.equals("Neue Bridge")?"":bridge.name,"Bridge-Name");addField(form,"Name",name);a=spinner(bats,bridge.batteryAId);b=spinner(bats,bridge.batteryBId);cable=spinnerOptional(cables,bridge.cableId,"— Kabel noch offen —");source=spinnerOptional(sources,bridge.sourceId,"— Quelle automatisch / offen —");String[] modes={"POOL","SEQUENZ","PASS_THROUGH","DIRECT_HARDWARE"};mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,modes));mode.setSelection(Math.max(0,Arrays.asList(modes).indexOf(bridge.mode)));addField(form,"Akku A",a);addField(form,"Akku B",b);addField(form,"Kabel",cable);addField(form,"Quelle / Eingang",source);addField(form,"Modus",mode);Button calc=secondary("VORSCHLAG NEU BERECHNEN");calc.setOnClickListener(v->updateSummary());form.addView(calc);add(root,form);
        LinearLayout result=card();result.addView(txt("Resultierender Zustand",18,TEXT,true));summary=txt("",14,CYAN,true);result.addView(summary);result.addView(txt("POOL = gemeinsame verfügbare Energie. SEQUENZ = Akku A zuerst, dann Akku B. PASS_THROUGH = Quelle versorgt Last und ggf. Akku gleichzeitig; Prognose nur mit bestätigten Daten. DIRECT_HARDWARE = nur dokumentieren, wenn die Hardware dafür zertifiziert ist.",11,MUTED,false));add(root,result);updateSummary();
        Button save=primary("BRIDGE SPEICHERN & AKTIVIEREN");save.setOnClickListener(v->save());add(root,save);Button cancel=secondary("ABBRECHEN");cancel.setOnClickListener(v->finish());add(root,cancel);return sv;}
    private void updateSummary(){ProfileStore.Profile pa=bats.get(a.getSelectedItemPosition()),pb=bats.get(b.getSelectedItemPosition());if(pa.id.equals(pb.id)){summary.setText("Akku A und B müssen verschieden sein.");summary.setTextColor(WARN);return;}double full=pa.capacityWh()+pb.capacityWh(),rem=0;int known=0;if(pa.socKnown){rem+=pa.capacityWh()*pa.estimatedSoc/100;known++;}if(pb.socKnown){rem+=pb.capacityWh()*pb.estimatedSoc/100;known++;}String cableName=cable.getSelectedItemPosition()==0?"offen":cables.get(cable.getSelectedItemPosition()-1).name;String srcName=source.getSelectedItemPosition()==0?"automatisch/offen":sources.get(source.getSelectedItemPosition()-1).name;String soc=known==2&&full>0?String.format(Locale.GERMANY,"%.0f %%",rem/full*100):"nicht vollständig bekannt";summary.setText("Akku A: "+pa.name+" · "+soc(pa)+"\nAkku B: "+pb.name+" · "+soc(pb)+"\nKabel: "+cableName+"\nQuelle: "+srcName+"\nGesamt: "+String.format(Locale.GERMANY,"%.1f Wh",rem)+" verfügbar von "+String.format(Locale.GERMANY,"%.1f Wh",full)+" · Gesamt-SOC "+soc);summary.setTextColor(CYAN);}
    private void save(){ProfileStore.Profile pa=bats.get(a.getSelectedItemPosition()),pb=bats.get(b.getSelectedItemPosition());if(pa.id.equals(pb.id)){toast("Akku A und B müssen verschieden sein.");return;}bridge.name=nonEmpty(name.getText().toString(),"Bridge · "+shortN(pa.name)+" + "+shortN(pb.name));bridge.batteryAId=pa.id;bridge.batteryBId=pb.id;bridge.cableId=cable.getSelectedItemPosition()==0?"":cables.get(cable.getSelectedItemPosition()-1).id;bridge.sourceId=source.getSelectedItemPosition()==0?"":sources.get(source.getSelectedItemPosition()-1).id;bridge.mode=String.valueOf(mode.getSelectedItem());bridge.updatedAt=System.currentTimeMillis();bridges.save(bridge);bridges.activate(bridge.id);setResult(RESULT_OK);finish();}
    private String soc(ProfileStore.Profile p){return p.socKnown?String.format(Locale.GERMANY,"%.0f%%",p.estimatedSoc):"SOC unbekannt";}private String shortN(String s){return s.length()>16?s.substring(0,16):s;}
    private Spinner spinner(List<ProfileStore.Profile> list,String selected){Spinner s=new Spinner(this);ArrayList<String> n=new ArrayList<>();for(ProfileStore.Profile p:list)n.add(p.name+" · "+soc(p));s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,n));for(int i=0;i<list.size();i++)if(list.get(i).id.equals(selected))s.setSelection(i);return s;}private Spinner spinnerOptional(List<ProfileStore.Profile> list,String selected,String empty){Spinner s=new Spinner(this);ArrayList<String> n=new ArrayList<>();n.add(empty);for(ProfileStore.Profile p:list)n.add(p.name);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,n));for(int i=0;i<list.size();i++)if(list.get(i).id.equals(selected))s.setSelection(i+1);return s;}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(round(PANEL,LINE,18));return c;}private void add(LinearLayout r,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.setMargins(0,0,0,dp(12));r.addView(v,p);}private void addField(LinearLayout c,String label,View v){TextView l=txt(label,11,MUTED,true);l.setPadding(0,dp(8),0,dp(2));c.addView(l);c.addView(v);}private TextView txt(String s,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private EditText input(String s,String hint){EditText e=new EditText(this);e.setText(s);e.setHint(hint);e.setTextColor(TEXT);e.setHintTextColor(MUTED);return e;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackground(round(BLUE,BLUE,18));b.setMinHeight(dp(62));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(CYAN);b.setBackground(round(PANEL,BLUE,15));b.setMinHeight(dp(52));return b;}private GradientDrawable round(int f,int s,int r){GradientDrawable g=new GradientDrawable();g.setColor(f);g.setStroke(dp(1),s);g.setCornerRadius(dp(r));return g;}private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private String nonEmpty(String s,String d){s=s==null?"":s.trim();return s.isEmpty()?d:s;}
}
