package com.ccop.usbcpowermonitor;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import org.json.*;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.regex.*;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(6,11,15),HEADER=Color.rgb(4,21,30),PANEL=Color.rgb(14,25,34),LINE=Color.rgb(43,61,74),TEXT=Color.rgb(247,249,252),MUTED=Color.rgb(151,164,178),BLUE=Color.rgb(24,153,255),CYAN=Color.rgb(73,194,255),OK=Color.rgb(48,214,132),WARN=Color.rgb(255,196,71),RED=Color.rgb(255,91,91);
    private static final int REQ_PHOTO=1001,REQ_EXPORT=2001;
    enum Tab{OVERVIEW,LIVE,PROFILES,BRIDGE,HISTORY,REPORT}
    private ProfileStore profileStore; private BridgeStore bridgeStore; private JSONObject telemetry=new JSONObject();
    private LinearLayout content,nav; private TextView headerStatus; private Tab current=Tab.OVERVIEW; private final Map<String,TextView> refs=new HashMap<>();
    private long historyRange=60L*60L*1000L; private String historyProfileId=""; private boolean lastPluggedUi=false; private boolean firstTelemetry=true;
    private ProfileStore.Profile pendingPhotoProfile; private String pendingExport="";
    private HistoryChartView powerChart,socChart; private DeviceSocChartView deviceChart;

    private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(TelemetryService.ACTION_TELEMETRY.equals(i.getAction()))updateTelemetry(i);}};

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(HEADER);getWindow().setNavigationBarColor(BG);profileStore=new ProfileStore(this);bridgeStore=new BridgeStore(this);setContentView(buildShell());showTab(Tab.OVERVIEW);startMonitor();if(Build.VERSION.SDK_INT>=33)try{requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},900);}catch(Throwable ignored){}}
    @Override protected void onResume(){super.onResume();IntentFilter f=new IntentFilter(TelemetryService.ACTION_TELEMETRY);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,f);}
    @Override protected void onPause(){try{unregisterReceiver(receiver);}catch(Throwable ignored){}super.onPause();}

    private View buildShell(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        root.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(0,in.getSystemWindowInsetTop(),0,in.getSystemWindowInsetBottom());return in;});
        LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(20),dp(12),dp(20),dp(12));h.setBackgroundColor(HEADER);
        LinearLayout titleRow=new LinearLayout(this);titleRow.setGravity(Gravity.CENTER_VERTICAL);ImageView icon=new ImageView(this);icon.setImageResource(R.drawable.ic_ccop_lademonitor);titleRow.addView(icon,new LinearLayout.LayoutParams(dp(56),dp(56)));LinearLayout texts=new LinearLayout(this);texts.setOrientation(LinearLayout.VERTICAL);texts.setPadding(dp(12),0,0,0);texts.addView(txt("CCOP LadeMonitor",30,TEXT,true));texts.addView(txt("ENERGIE. IMMER. ÜBERALL.",12,MUTED,true));titleRow.addView(texts,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));h.addView(titleRow);
        headerStatus=txt("● Live-Monitor startet …",14,OK,false);headerStatus.setPadding(dp(4),dp(8),0,0);h.addView(headerStatus);root.addView(h);
        FrameLayout frame=new FrameLayout(this);content=new LinearLayout(this);frame.addView(content,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));root.addView(frame,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));
        nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setBackgroundColor(Color.rgb(5,16,23));nav.setPadding(dp(4),dp(3),dp(4),dp(3));addNav(Tab.OVERVIEW,"⌂\nÜbersicht");addNav(Tab.LIVE,"⌁\nLive");addNav(Tab.PROFILES,"▱\nProfile");addNav(Tab.BRIDGE,"⌘\nBridge");addNav(Tab.HISTORY,"◷\nVerlauf");addNav(Tab.REPORT,"▥\nBericht");root.addView(nav,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(70)));return root;
    }
    private void addNav(Tab t,String s){TextView v=txt(s,11,MUTED,true);v.setGravity(Gravity.CENTER);v.setOnClickListener(x->showTab(t));nav.addView(v,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.MATCH_PARENT,1));v.setTag(t);}
    private void updateNav(){for(int i=0;i<nav.getChildCount();i++){TextView v=(TextView)nav.getChildAt(i);v.setTextColor(v.getTag()==current?CYAN:MUTED);}}
    private void showTab(Tab t){current=t;refs.clear();content.removeAllViews();ScrollView s=new ScrollView(this);s.setFillViewport(true);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(20),dp(20),dp(24));s.addView(body);content.addView(s,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));if(t==Tab.OVERVIEW)buildOverview(body);else if(t==Tab.LIVE)buildLive(body);else if(t==Tab.PROFILES)buildProfiles(body);else if(t==Tab.BRIDGE)buildBridge(body);else if(t==Tab.HISTORY)buildHistory(body);else buildReport(body);updateNav();updateVisible();}

    private void sectionHeader(LinearLayout b,String title,String sub){b.addView(txt(title,31,TEXT,true));TextView s=txt(sub,15,MUTED,false);s.setPadding(0,dp(3),0,dp(16));b.addView(s);}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(round(PANEL,LINE,18));return c;}
    private void addCard(LinearLayout b,View c){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.setMargins(0,0,0,dp(12));b.addView(c,p);}
    private TextView ref(String key,String initial,int size,int color,boolean bold){TextView v=txt(initial,size,color,bold);refs.put(key,v);return v;}
    private TextView metricRow(String label,String key){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView l=txt(label,14,MUTED,false),v=ref(key,"—",15,TEXT,true);r.addView(l,new LinearLayout.LayoutParams(0,dp(40),1));r.addView(v,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,dp(40)));refs.put("ROW_"+key,v);return v;}
    private void addMetric(LinearLayout c,String label,String key){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(txt(label,14,MUTED,false),new LinearLayout.LayoutParams(0,dp(40),1));TextView v=ref(key,"—",15,TEXT,true);v.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);r.addView(v);c.addView(r);}

    private void buildOverview(LinearLayout b){
        sectionHeader(b,"Gesamtenergie & Gerätepool","Nur gemessene oder bestätigte Daten. Keine Demo-Werte.");
        if(isPlugged()&&profileStore.getActive()==null){Button assign=primary("QUELLE / POWERBANK ZUORDNEN");assign.setOnClickListener(v->promptSourceSelection());addCard(b,assign);}
        LinearLayout total=card();total.addView(txt("Gesamtenergie",19,TEXT,true));TextView pct=ref("aggPct","— %",46,BLUE,true);total.addView(pct);ProgressBar pb=progress();refs.put("aggBarHolder",pct);total.addView(pb,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(8)));pb.setTag("aggBar");TextView wh=ref("aggWh","— Wh verfügbar",13,MUTED,false);wh.setPadding(0,dp(8),0,0);total.addView(wh);addCard(b,total);
        LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);LinearLayout speed=smallCard("Ladegeschwindigkeit");speed.addView(ref("ovPower","— W",24,TEXT,true));speed.addView(ref("ovCurrent","— mA",12,MUTED,false));LinearLayout source=smallCard("Aktive Quelle");source.addView(ref("ovSource","Keine Quelle",18,TEXT,true));source.addView(ref("ovSourceState","nicht verbunden",12,MUTED,false));row.addView(speed,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1);rp.setMargins(dp(10),0,0,0);row.addView(source,rp);addCard(b,row);
        LinearLayout runtime=card();runtime.addView(txt("Laufzeit-Prognose",17,TEXT,true));runtime.addView(ref("runtime","—",28,CYAN,true));runtime.addView(txt("Berechnet aus bekannter Gesamt-Restenergie und aktuellem Geräteverbrauch. Bei aktiver Ladung wird keine künstliche Laufzeit ausgegeben.",12,MUTED,false));addCard(b,runtime);
        LinearLayout bridge=card();bridge.addView(txt("Aktive Bridge",17,TEXT,true));bridge.addView(ref("ovBridge","Keine Bridge aktiv",17,CYAN,true));bridge.addView(ref("ovBridgeInfo","Bridge kann im Tab Bridge erstellt und aktiviert werden.",12,MUTED,false));bridge.setOnClickListener(v->showTab(Tab.BRIDGE));addCard(b,bridge);
        LinearLayout devices=card();devices.addView(txt("Geräte im System",18,TEXT,true));devices.addView(deviceRowPhone());for(ProfileStore.Profile p:profileStore.loadActiveInventory())devices.addView(deviceRow(p));addCard(b,devices);
        Button go=primary("▶  LIVE ÜBERWACHEN  ›");go.setOnClickListener(v->showTab(Tab.LIVE));addCard(b,go);
    }
    private LinearLayout smallCard(String label){LinearLayout c=card();c.addView(txt(label,13,MUTED,false));return c;}
    private View deviceRowPhone(){LinearLayout r=deviceBase();LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.VERTICAL);left.addView(txt("Smartphone",16,TEXT,true));left.addView(txt("Android · live",12,MUTED,false));r.addView(left,new LinearLayout.LayoutParams(0,dp(58),1));TextView s=ref("phoneDeviceSoc","— %",17,CYAN,true);r.addView(s);return r;}
    private View deviceRow(ProfileStore.Profile p){LinearLayout r=deviceBase();LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.addView(txt(p.name,16,TEXT,true));String meta=p.type+" · "+(p.deviceHash==null?"":p.deviceHash);l.addView(txt(meta,11,MUTED,false));r.addView(l,new LinearLayout.LayoutParams(0,dp(62),1));String soc=p.isEnergyStore()?(p.socKnown?fmt0(p.estimatedSoc)+" %":"SOC ?"):("CABLE".equals(p.type)?"Kabel":"Quelle");TextView v=txt(soc,16,p.socKnown?CYAN:MUTED,true);r.addView(v);r.setOnClickListener(x->showProfileDialog(p));return r;}
    private LinearLayout deviceBase(){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(4),dp(7),dp(4),dp(7));return r;}

    private void buildLive(LinearLayout b){
        sectionHeader(b,"Live-Messung","Android BatteryManager + verfügbare USB/VBUS/OEM-Knoten. Fehlende Werte bleiben fehlend.");
        LinearLayout hero=card();hero.addView(txt("Ladegeschwindigkeit LIVE",18,TEXT,true));hero.addView(ref("liveMa","— mA",48,BLUE,true));hero.addView(ref("liveAW","— A  ·  — W netto",21,TEXT,true));hero.addView(ref("liveState","Kein Ladegerät erkannt",13,MUTED,false));addCard(b,hero);
        LinearLayout battery=card();battery.addView(txt("Smartphone-Akku · direkt",17,TEXT,true));addMetric(battery,"Akkustand","livePhonePct");addMetric(battery,"Akkuspannung","liveBattV");addMetric(battery,"Netto-Strom","liveBattA");addMetric(battery,"Netto-Leistung","liveBattW");addMetric(battery,"Temperatur","liveTemp");addCard(b,battery);
        LinearLayout source=card();source.addView(txt("Angeschlossene Quelle",17,TEXT,true));addMetric(source,"Profil / Modell","liveSourceName");addMetric(source,"Quellenspannung LIVE","liveSourceV");addMetric(source,"Quellenstrom LIVE","liveSourceA");addMetric(source,"Quellenleistung","liveSourceW");addMetric(source,"Powerbank-SOC","liveSourceSoc");addMetric(source,"Android MAX-Profil","liveMax");Button choose=secondary("QUELLE BESTÄTIGEN / WECHSELN");choose.setOnClickListener(v->promptSourceSelection());source.addView(choose);addCard(b,source);
        LinearLayout charts=card();charts.addView(txt("Live-Verlauf · 1 Stunde",17,TEXT,true));powerChart=new HistoryChartView(this,HistoryChartView.Mode.POWER);socChart=new HistoryChartView(this,HistoryChartView.Mode.SOC);charts.addView(powerChart,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(210)));charts.addView(socChart,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(210)));addCard(b,charts);refreshCharts();
    }

    private void buildProfiles(LinearLayout b){
        sectionHeader(b,"Profile & Inventar","Powerbanks, Netzteile, Kabel und externe Akkus. Editieren, validieren, fotografieren und archivieren.");
        Button source=secondary("LADEQUELLE AUSWÄHLEN");source.setOnClickListener(v->promptSourceSelection());addCard(b,source);
        List<ProfileStore.Profile> list=profileStore.load();int active=0,arch=0;for(ProfileStore.Profile p:list)if(p.archived)arch++;else active++;TextView meta=txt(active+" aktive Profile · "+arch+" archiviert",12,MUTED,false);meta.setPadding(0,0,0,dp(10));b.addView(meta);
        for(ProfileStore.Profile p:list){LinearLayout c=card();c.setAlpha(p.archived?.55f:1f);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(txt(p.name,19,TEXT,true));names.addView(txt(p.type+" · Hash "+p.deviceHash+(p.archived?" · ARCHIV":""),11,MUTED,false));top.addView(names,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));if(p.id.equals(profileStore.getActiveId()))top.addView(txt("AKTIV",11,OK,true));c.addView(top);if(p.isEnergyStore()){c.addView(txt((p.capacityWh()>0?fmt1(p.capacityWh())+" Wh":"Kapazität offen")+" · "+(p.socKnown?"SOC "+fmt0(p.estimatedSoc)+"% · "+p.socOrigin:"SOC nicht bestätigt"),13,p.socKnown?CYAN:WARN,false));}else if("CABLE".equals(p.type)){c.addView(txt("Max. "+(p.cableMaxW>0?fmt0(p.cableMaxW)+" W":"offen")+" · E-Marker "+(p.cableEMarked?"Ja":"Nein")+" · Qualität "+(Double.isNaN(p.cableQuality)?"nicht gemessen":fmt0(p.cableQuality)+"/100"),13,CYAN,false));}c.addView(txt(p.photoUris.size()+" Foto(s) · zuletzt gesehen "+dateShort(p.lastSeenAt),11,MUTED,false));LinearLayout buttons=new LinearLayout(this);Button open=mini("ÖFFNEN");open.setOnClickListener(v->showProfileDialog(p));Button act=mini("ALS QUELLE");act.setOnClickListener(v->{p.archived=false;p.lastSeenAt=System.currentTimeMillis();profileStore.saveProfile(p);profileStore.setActiveId(p.id);showTab(Tab.PROFILES);});Button archive=mini(p.archived?"REAKTIVIEREN":"ARCHIV");archive.setOnClickListener(v->{profileStore.archiveProfile(p.id,!p.archived);showTab(Tab.PROFILES);});buttons.addView(open,new LinearLayout.LayoutParams(0,dp(44),1));buttons.addView(act,new LinearLayout.LayoutParams(0,dp(44),1));buttons.addView(archive,new LinearLayout.LayoutParams(0,dp(44),1));c.addView(buttons);addCard(b,c);}
        Button add=primary("＋  NEUES PROFIL ANLEGEN  ›");add.setOnClickListener(v->showProfileDialog(null));addCard(b,add);
    }

    private void showProfileDialog(ProfileStore.Profile existing){
        ProfileStore.Profile p=existing==null?new ProfileStore.Profile():existing;pendingPhotoProfile=p;
        ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(8),dp(20),dp(8));sv.addView(box);
        EditText name=input(p.name,"Gerätename / Modell");box.addView(name);Spinner type=new Spinner(this);String[] types={"POWERBANK","EXTERNAL_BATTERY","CHARGER","CABLE"};ArrayAdapter<String> ta=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,types);type.setAdapter(ta);type.setSelection(Math.max(0,Arrays.asList(types).indexOf(p.type)));box.addView(type);
        EditText mah=input(p.capacityMah>0?fmtNoGroup(p.capacityMah):"","Kapazität mAh");EditText nv=input(p.nominalV>0?fmtNoGroup(p.nominalV):"","Nennspannung V");EditText soc=input(p.socKnown?fmtNoGroup(p.estimatedSoc):"","SOC % (leer = unbekannt)");EditText eff=input(fmtNoGroup(p.efficiency*100),"Wirkungsgrad %");EditText maxv=input(p.profileMaxVoltage>0?fmtNoGroup(p.profileMaxVoltage):"","Max. V");EditText maxa=input(p.profileMaxCurrent>0?fmtNoGroup(p.profileMaxCurrent):"","Max. A");box.addView(mah);box.addView(nv);box.addView(soc);box.addView(eff);box.addView(maxv);box.addView(maxa);
        EditText cableW=input(p.cableMaxW>0?fmtNoGroup(p.cableMaxW):"","Kabel max. W");EditText cableL=input(p.cableLengthM>0?fmtNoGroup(p.cableLengthM):"","Kabellänge m");box.addView(cableW);box.addView(cableL);CheckBox em=new CheckBox(this);em.setText("E-Marker vorhanden");em.setTextColor(TEXT);em.setChecked(p.cableEMarked);box.addView(em);CheckBox pass=new CheckBox(this);pass.setText("Pass-through unterstützt");pass.setTextColor(TEXT);pass.setChecked(p.passthrough);box.addView(pass);
        EditText note=input(p.note,"Notiz");note.setMinLines(2);box.addView(note);box.addView(txt("Hash: "+p.deviceHash+" · Fotos: "+p.photoUris.size(),12,MUTED,false));
        if(!p.photoUris.isEmpty()){HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout imgs=new LinearLayout(this);for(String u:p.photoUris){try{ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setImageURI(Uri.parse(u));imgs.addView(im,new LinearLayout.LayoutParams(dp(120),dp(90)));}catch(Exception ignored){}}hs.addView(imgs);box.addView(hs,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(100)));}
        Button photo=secondary("FOTO HINZUFÜGEN + OCR");photo.setOnClickListener(v->{p.name=name.getText().toString().trim();p.type=types[type.getSelectedItemPosition()];p.capacityMah=dbl(mah.getText().toString(),0);p.nominalV=dbl(nv.getText().toString(),0);pendingPhotoProfile=p;choosePhoto();});box.addView(photo);
        if("CABLE".equals(p.type)||"CABLE".equals(types[type.getSelectedItemPosition()])){Button test=secondary("KABELQUALITÄT AUS LIVE-MESSUNGEN PRÜFEN");test.setOnClickListener(v->testCable(p));box.addView(test);}
        AlertDialog d=new AlertDialog.Builder(this).setTitle(existing==null?"Neues Profil":"Profil-Detail").setView(sv).setNegativeButton("ABBRECHEN",null).setNeutralButton(existing!=null?(p.archived?"REAKTIVIEREN":"ARCHIVIEREN"):"",null).setPositiveButton("SPEICHERN",null).create();
        d.setOnShowListener(x->{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{p.name=nonEmpty(name.getText().toString(),"Unbenanntes Gerät");p.type=types[type.getSelectedItemPosition()];p.capacityMah=dbl(mah.getText().toString(),0);p.nominalV=dbl(nv.getText().toString(),0);String ss=soc.getText().toString().trim();if(ss.isEmpty()){p.socKnown=false;p.estimatedSoc=Double.NaN;p.socOrigin="UNBEKANNT";}else{p.estimatedSoc=clamp(dbl(ss,0),0,100);p.socKnown=true;p.socOrigin="MANUAL";p.lastValidatedSoc=p.estimatedSoc;p.lastValidationAt=System.currentTimeMillis();}p.efficiency=clamp(dbl(eff.getText().toString(),88)/100.0,.5,1);p.profileMaxVoltage=dbl(maxv.getText().toString(),0);p.profileMaxCurrent=dbl(maxa.getText().toString(),0);p.cableMaxW=dbl(cableW.getText().toString(),0);p.cableLengthM=dbl(cableL.getText().toString(),0);p.cableEMarked=em.isChecked();p.passthrough=pass.isChecked();p.note=note.getText().toString();profileStore.saveProfile(p);d.dismiss();showTab(Tab.PROFILES);});if(existing!=null){d.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{profileStore.archiveProfile(p.id,!p.archived);d.dismiss();showTab(Tab.PROFILES);});}});d.show();
    }

    private void buildBridge(LinearLayout b){
        sectionHeader(b,"Bridge konfigurieren","Logischer Energiepool und Zuordnung. Die App verbindet Akkus nicht elektrisch.");
        LinearLayout safety=card();safety.addView(txt("ⓘ Direkte Bridge nur mit dafür zertifizierter Hardware",14,WARN,true));safety.addView(txt("Powerbanks/Akkus niemals allein aufgrund dieser App parallel oder direkt zusammenschalten. Die Bridge-Funktion dokumentiert und berechnet Kombinationen; elektrische Sicherheit muss die Hardware gewährleisten.",12,MUTED,false));addCard(b,safety);
        BridgeStore.Bridge active=bridgeStore.active();LinearLayout state=card();state.addView(txt("Aktive Bridge",17,TEXT,true));state.addView(ref("bridgeActive",active==null?"Keine Bridge aktiv":active.name,21,CYAN,true));if(active!=null)state.addView(txt(bridgeDescription(active),13,MUTED,false));addCard(b,state);
        List<BridgeStore.Bridge> all=bridgeStore.load();for(BridgeStore.Bridge br:all)if(!br.archived){LinearLayout c=card();c.addView(txt(br.name+(br.active?" · AKTIV":""),18,TEXT,true));c.addView(txt(bridgeDescription(br),13,MUTED,false));LinearLayout rr=new LinearLayout(this);Button edit=mini("BEARBEITEN");edit.setOnClickListener(v->showBridgeDialog(br));Button act=mini("AKTIVIEREN");act.setOnClickListener(v->{bridgeStore.activate(br.id);showTab(Tab.BRIDGE);});Button ar=mini("ARCHIV");ar.setOnClickListener(v->{bridgeStore.archive(br.id);showTab(Tab.BRIDGE);});rr.addView(edit,new LinearLayout.LayoutParams(0,dp(44),1));rr.addView(act,new LinearLayout.LayoutParams(0,dp(44),1));rr.addView(ar,new LinearLayout.LayoutParams(0,dp(44),1));c.addView(rr);addCard(b,c);}
        Button add=primary("＋  NEUE BRIDGE ERSTELLEN  ›");add.setOnClickListener(v->showBridgeDialog(null));addCard(b,add);Button suggest=secondary("PASSENDE KOMBINATION VORSCHLAGEN");suggest.setOnClickListener(v->suggestBridge());addCard(b,suggest);
    }
    private String bridgeDescription(BridgeStore.Bridge br){return "Akku A: "+profileName(br.batteryAId)+" · Akku B: "+profileName(br.batteryBId)+"\nKabel: "+profileName(br.cableId)+" · Quelle: "+profileName(br.sourceId)+" · Modus: "+br.mode;}
    private void showBridgeDialog(BridgeStore.Bridge existing){List<ProfileStore.Profile> bats=new ArrayList<>(),cables=new ArrayList<>(),sources=new ArrayList<>();for(ProfileStore.Profile p:profileStore.loadActiveInventory()){if(p.isEnergyStore())bats.add(p);if("CABLE".equals(p.type))cables.add(p);if(!"CABLE".equals(p.type))sources.add(p);}if(bats.size()<2){toast("Für eine Bridge werden mindestens zwei Akku-/Powerbank-Profile benötigt.");return;}BridgeStore.Bridge br=existing==null?new BridgeStore.Bridge():existing;LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),0,dp(20),0);EditText name=input(br.name,"Bridge-Name");box.addView(name);Spinner a=profileSpinner(bats,br.batteryAId),bb=profileSpinner(bats,br.batteryBId),c=profileSpinner(cables,br.cableId),src=profileSpinner(sources,br.sourceId);box.addView(label("Akku A"));box.addView(a);box.addView(label("Akku B"));box.addView(bb);box.addView(label("Kabel"));box.addView(c);box.addView(label("Quelle / Eingang"));box.addView(src);String[] modes={"POOL","SEQUENZ","PASS_THROUGH","DIRECT_HARDWARE"};Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,modes));mode.setSelection(Math.max(0,Arrays.asList(modes).indexOf(br.mode)));box.addView(label("Modus"));box.addView(mode);new AlertDialog.Builder(this).setTitle("Bridge konfigurieren").setView(box).setNegativeButton("ABBRECHEN",null).setPositiveButton("SPEICHERN",(d,w)->{br.name=nonEmpty(name.getText().toString(),"Bridge");br.batteryAId=idAt(bats,a);br.batteryBId=idAt(bats,bb);if(br.batteryAId.equals(br.batteryBId)){toast("Akku A und B müssen verschieden sein.");return;}br.cableId=idAt(cables,c);br.sourceId=idAt(sources,src);br.mode=modes[mode.getSelectedItemPosition()];br.updatedAt=System.currentTimeMillis();bridgeStore.save(br);showTab(Tab.BRIDGE);}).show();}
    private void suggestBridge(){List<ProfileStore.Profile>bats=new ArrayList<>(),cables=new ArrayList<>();for(ProfileStore.Profile p:profileStore.loadActiveInventory()){if(p.isEnergyStore())bats.add(p);if("CABLE".equals(p.type))cables.add(p);}if(bats.size()<2){toast("Noch keine passende Kombination: mindestens zwei Akkus erforderlich.");return;}String msg="Vorschlag: "+bats.get(0).name+" + "+bats.get(1).name+(cables.isEmpty()?" · Kabelprofil fehlt":" · "+cables.get(0).name)+"\n\nSOC A: "+socLabel(bats.get(0))+" · SOC B: "+socLabel(bats.get(1));new AlertDialog.Builder(this).setTitle("Bridge-Vorschlag").setMessage(msg).setNegativeButton("SPÄTER",null).setPositiveButton("KONFIGURIEREN",(d,w)->showBridgeDialog(null)).show();}

    private void buildHistory(LinearLayout b){
        sectionHeader(b,"Ladeverlauf & Ladezyklen","Laden UND Entladen über Zeit. Zeitraum frei wählbar; Unterbrechungen bleiben sichtbar.");
        LinearLayout ranges=new LinearLayout(this);String[] labels={"15m","1h","6h","24h","Alle","Frei"};long[] vals={900000,3600000,21600000,86400000,0,-1};for(int i=0;i<labels.length;i++){Button bt=mini(labels[i]);final long v=vals[i];bt.setOnClickListener(x->{if(v<0)customRange();else{historyRange=v;showTab(Tab.HISTORY);}});ranges.addView(bt,new LinearLayout.LayoutParams(0,dp(46),1));}addCard(b,ranges);
        LinearLayout p=card();p.addView(txt("Lade-/Entladeleistung (W)",18,TEXT,true));powerChart=new HistoryChartView(this,HistoryChartView.Mode.POWER);p.addView(powerChart,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(245)));addCard(b,p);
        LinearLayout s=card();s.addView(txt("Smartphone / Quelle / Gesamt-SOC",18,TEXT,true));socChart=new HistoryChartView(this,HistoryChartView.Mode.SOC);s.addView(socChart,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(245)));addCard(b,s);
        List<ProfileStore.Profile> energy=new ArrayList<>();for(ProfileStore.Profile x:profileStore.loadActiveInventory())if(x.isEnergyStore())energy.add(x);if(!energy.isEmpty()){LinearLayout d=card();d.addView(txt("Geräteverlauf · einzelner Akku",18,TEXT,true));Spinner sp=profileSpinner(energy,historyProfileId);if(historyProfileId.isEmpty())historyProfileId=energy.get(0).id;sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){historyProfileId=energy.get(pos).id;refreshDeviceChart();}public void onNothingSelected(android.widget.AdapterView<?>p){}});d.addView(sp);deviceChart=new DeviceSocChartView(this);d.addView(deviceChart,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(220)));addCard(b,d);}
        LinearLayout stats=card();stats.addView(txt("Aktueller Zyklus",17,TEXT,true));addMetric(stats,"Energie netto","histCycleWh");addMetric(stats,"Messpunkte","histCount");addMetric(stats,"Zeitraum","histRange");addCard(b,stats);refreshCharts();
    }
    private void customRange(){EditText e=input("180","Minuten (z. B. 180)");new AlertDialog.Builder(this).setTitle("Freier Zeitraum").setView(e).setNegativeButton("ABBRECHEN",null).setPositiveButton("ÜBERNEHMEN",(d,w)->{double m=dbl(e.getText().toString(),60);historyRange=(long)(Math.max(1,m)*60000L);showTab(Tab.HISTORY);}).show();}

    private void buildReport(LinearLayout b){sectionHeader(b,"Bericht & Entwicklungsauftrag","Messdaten, Inventar, Bridge und fehlende Telemetrie lokal exportieren.");LinearLayout diag=card();diag.addView(txt("Live-Diagnose",18,TEXT,true));addMetric(diag,"Ladegerät verbunden","repPlugged");addMetric(diag,"Laden aktiv","repCharging");addMetric(diag,"SOURCE_V","repV");addMetric(diag,"SOURCE_A","repA");addMetric(diag,"Aktives Profil","repProfile");addMetric(diag,"Inventar","repInventory");addMetric(diag,"Bridges","repBridges");addMetric(diag,"Historie","repHistory");addCard(b,diag);LinearLayout issues=card();issues.addView(txt("Automatisch erkannte Entwicklungsaufträge",18,TEXT,true));issues.addView(ref("repIssues","Prüfung läuft …",13,WARN,false));addCard(b,issues);Button export=primary("BERICHT ALS JSON EXPORTIEREN");export.setOnClickListener(v->exportReport());addCard(b,export);Button clear=secondary("VERLAUF ZURÜCKSETZEN");clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Verlauf löschen?").setMessage("Nur die lokale Messhistorie wird gelöscht. Profile und Bridges bleiben erhalten.").setNegativeButton("ABBRECHEN",null).setPositiveButton("LÖSCHEN",(d,w)->{HistoryStore.clear(this);showTab(Tab.REPORT);}).show());addCard(b,clear);}

    private void updateTelemetry(Intent i){try{JSONObject o=new JSONObject();for(String k:new String[]{"ts","charging","plugged","plugType","phonePct","batteryV","batteryA","batteryMa","batteryW","batteryAvgMa","chargeCounterMah","temperatureC","profileMaxV","profileMaxA","sourceV","sourceA","sourceExactW","sourceEffectiveW","sourcePowerEstimated","sourceDirectSoc","sourceType","profileId","profileName","profileType","profilePassthrough","profileCapacityWh","sourceSoc","aggregateSoc","aggregateRemainingWh","aggregateFullWh","aggregateKnownCount","aggregateUnknownCount","cycleNetWh","cycleSourceWh","totalNetWh","totalSourceWh","cycleId","historyCount"})if(i.hasExtra(k)){Object v=i.getExtras().get(k);o.put(k,v);}telemetry=o;}catch(Exception ignored){}boolean plugged=isPlugged();boolean was=lastPluggedUi;if(firstTelemetry){lastPluggedUi=plugged;firstTelemetry=false;}else{lastPluggedUi=plugged;if(plugged&&!was)new Handler(Looper.getMainLooper()).postDelayed(this::promptSourceSelection,300);}updateHeader();updateVisible();}
    private void updateHeader(){boolean plugged=isPlugged(),charging=bool("charging");ProfileStore.Profile a=profileStore.getActive();String s=!plugged?"● Kein Ladegerät · Smartphone "+fmt0(val("phonePct"))+" %":(charging?"● Laden aktiv":"● Quelle verbunden")+"  ⚡ "+(a!=null?a.name:str("plugType","Quelle"))+"  ◉ "+fmt0(val("phonePct"))+" %";headerStatus.setText(s);headerStatus.setTextColor(plugged?OK:MUTED);}
    private void updateVisible(){if(current==Tab.OVERVIEW)updateOverview();else if(current==Tab.LIVE)updateLive();else if(current==Tab.HISTORY){updateHistoryStats();refreshCharts();}else if(current==Tab.BRIDGE)updateBridgeLive();else if(current==Tab.REPORT)updateReport();}
    private void updateOverview(){double agg=val("aggregateSoc"),rem=val("aggregateRemainingWh"),full=val("aggregateFullWh");set("aggPct",finite(agg)?fmt0(agg)+" %":"— %");set("aggWh",(finite(rem)?fmt1(rem)+" Wh verfügbar":"—")+" · "+(finite(full)?fmt1(full)+" Wh bekannt":"keine bestätigten externen Akkus")+(telemetry.optInt("aggregateUnknownCount",0)>0?" · "+telemetry.optInt("aggregateUnknownCount",0)+" SOC unbekannt":""));TextView barHolder=refs.get("aggBarHolder");if(barHolder!=null&&barHolder.getParent() instanceof LinearLayout){LinearLayout parent=(LinearLayout)barHolder.getParent();for(int i=0;i<parent.getChildCount();i++)if(parent.getChildAt(i) instanceof ProgressBar)((ProgressBar)parent.getChildAt(i)).setProgress(finite(agg)?(int)Math.round(agg):0);}double w=val("batteryW"),ma=val("batteryMa");set("ovPower",bool("charging")&&finite(w)?fmt1(Math.abs(w))+" W":"0 W");set("ovCurrent",finite(ma)?fmt0(Math.abs(ma))+" mA":"— mA");ProfileStore.Profile a=profileStore.getActive();set("ovSource",isPlugged()?(a!=null?a.name:"Quelle nicht zugeordnet"):"Keine Quelle");set("ovSourceState",isPlugged()?(bool("charging")?"Laden aktiv":"verbunden, nicht ladend"):"nicht verbunden");BridgeStore.Bridge br=bridgeStore.active();set("ovBridge",br==null?"Keine Bridge aktiv":br.name+" · "+br.mode);set("ovBridgeInfo",br==null?"Im Bridge-Tab konfigurieren.":bridgeDescription(br));set("phoneDeviceSoc",finite(val("phonePct"))?fmt0(val("phonePct"))+" %":"—");if(!isPlugged()&&finite(w)&&w>.05&&finite(rem))set("runtime",formatHours(rem/Math.abs(w))+" geschätzt");else set("runtime",isPlugged()?"Während aktiver Quelle nicht berechnet":"Noch keine belastbare Verbrauchsleistung");}
    private void updateLive(){double ma=val("batteryMa"),a=val("batteryA"),w=val("batteryW");set("liveMa",finite(ma)?fmt0(Math.abs(ma))+" mA":"— mA");set("liveAW",(finite(a)?fmt2(Math.abs(a))+" A":"— A")+"  ·  "+(finite(w)?fmt2(Math.abs(w))+" W netto":"— W"));set("liveState",!isPlugged()?"Kein Ladegerät angeschlossen":(bool("charging")?"Laden aktiv · echte Android-Livewerte":"Quelle verbunden · kein aktiver Ladevorgang"));set("livePhonePct",finite(val("phonePct"))?fmt0(val("phonePct"))+" %":"—");set("liveBattV",finite(val("batteryV"))?fmt3(val("batteryV"))+" V":"—");set("liveBattA",finite(a)?fmt3(a)+" A":"—");set("liveBattW",finite(w)?fmt2(Math.abs(w))+" W":"—");set("liveTemp",finite(val("temperatureC"))?fmt1(val("temperatureC"))+" °C":"—");ProfileStore.Profile p=profileStore.getActive();set("liveSourceName",isPlugged()?(p!=null?p.name:"nicht zugeordnet"):"keine");set("liveSourceV",finite(val("sourceV"))?fmt3(val("sourceV"))+" V · LIVE":"nicht vom System freigegeben");set("liveSourceA",finite(val("sourceA"))?fmt3(val("sourceA"))+" A · LIVE":"nicht vom System freigegeben");set("liveSourceW",finite(val("sourceExactW"))?fmt2(val("sourceExactW"))+" W · DIREKT":(finite(val("sourceEffectiveW"))?fmt2(val("sourceEffectiveW"))+" W · aus Akku netto modelliert":"—"));set("liveSourceSoc",p!=null&&p.isEnergyStore()&&p.socKnown?fmt0(p.estimatedSoc)+" % · "+p.socOrigin:"nicht gemeldet / nicht bestätigt");set("liveMax",(finite(val("profileMaxV"))?fmt1(val("profileMaxV"))+" V":"—")+" / "+(finite(val("profileMaxA"))?fmt1(val("profileMaxA"))+" A":"—")+" · MAX, nicht Live");refreshCharts();}
    private void updateBridgeLive(){BridgeStore.Bridge br=bridgeStore.active();set("bridgeActive",br==null?"Keine Bridge aktiv":br.name);}
    private void updateHistoryStats(){set("histCycleWh",finite(val("cycleNetWh"))?fmt3(val("cycleNetWh"))+" Wh":"0 Wh");set("histCount",String.valueOf(HistoryStore.count(this)));set("histRange",historyRange==0?"Gesamt":formatRange(historyRange));}
    private void updateReport(){set("repPlugged",isPlugged()?"JA":"NEIN");set("repCharging",bool("charging")?"JA":"NEIN");set("repV",finite(val("sourceV"))?fmt3(val("sourceV"))+" V":"UNAVAILABLE");set("repA",finite(val("sourceA"))?fmt3(val("sourceA"))+" A":"UNAVAILABLE");ProfileStore.Profile p=profileStore.getActive();set("repProfile",p==null?"keins":p.name);set("repInventory",profileStore.load().size()+" Profile");set("repBridges",bridgeStore.load().size()+" Bridges");set("repHistory",HistoryStore.count(this)+" Messpunkte");StringBuilder x=new StringBuilder();if(!finite(val("sourceV")))x.append("P0 · SOURCE_V wird vom Gerät nicht bereitgestellt.\n");if(!finite(val("sourceA")))x.append("P0 · SOURCE_A wird vom Gerät nicht bereitgestellt.\n");if(isPlugged()&&p==null)x.append("P0 · Quelle verbunden, aber keinem Profil zugeordnet.\n");for(ProfileStore.Profile q:profileStore.loadActiveInventory())if(q.isEnergyStore()&&!q.socKnown)x.append("P1 · SOC fehlt: ").append(q.name).append(". Manuell bestätigen oder direkte Telemetrie nutzen.\n");if(x.length()==0)x.append("Keine offenen Telemetrie-Probleme erkannt.");set("repIssues",x.toString());}
    private void refreshCharts(){long since=historyRange==0?0:System.currentTimeMillis()-historyRange;List<HistoryStore.Point> pts=HistoryStore.readSince(this,since,800);if(powerChart!=null)powerChart.setPoints(pts);if(socChart!=null)socChart.setPoints(pts);refreshDeviceChart();}
    private void refreshDeviceChart(){if(deviceChart==null||historyProfileId.isEmpty())return;long since=historyRange==0?0:System.currentTimeMillis()-historyRange;ProfileStore.Profile p=profileStore.getById(historyProfileId);deviceChart.setData(HistoryStore.readForProfile(this,historyProfileId,since,500),historyProfileId,p==null?"Gerät":p.name);}

    private void promptSourceSelection(){if(!isPlugged()){toast("Aktuell ist keine externe Ladequelle angeschlossen.");return;}List<ProfileStore.Profile> opts=new ArrayList<>();for(ProfileStore.Profile p:profileStore.loadActiveInventory())if(!"CABLE".equals(p.type))opts.add(p);ArrayList<String> names=new ArrayList<>();for(ProfileStore.Profile p:opts)names.add(p.name+" · "+p.type+(p.socKnown?" · "+fmt0(p.estimatedSoc)+"%":""));names.add("＋ Neues Gerät / neue Powerbank anlegen");new AlertDialog.Builder(this).setTitle("Welche Quelle ist jetzt angeschlossen?").setMessage("Android erkennt den Stromanschluss, aber nicht bei jedem USB-C-Gerät das Modell. Bitte Profil bestätigen; es werden keine Demo-Geräte angenommen.").setItems(names.toArray(new String[0]),(d,which)->{if(which<opts.size()){ProfileStore.Profile p=opts.get(which);p.lastSeenAt=System.currentTimeMillis();profileStore.saveProfile(p);profileStore.setActiveId(p.id);if(p.isEnergyStore()&&!p.socKnown)askManualSoc(p);else maybeSuggestBridge(p);}else showProfileDialog(null);updateVisible();}).show();}
    private void askManualSoc(ProfileStore.Profile p){EditText e=input("","Anzeige an Powerbank in %");new AlertDialog.Builder(this).setTitle("SOC bestätigen · "+p.name).setMessage("Falls die Powerbank selbst einen Prozentwert anzeigt, hier eintragen. Ohne Bestätigung bleibt der SOC unbekannt.").setView(e).setNegativeButton("UNBEKANNT",(d,w)->maybeSuggestBridge(p)).setPositiveButton("BESTÄTIGEN",(d,w)->{String s=e.getText().toString().trim();if(!s.isEmpty()){p.estimatedSoc=clamp(dbl(s,0),0,100);p.socKnown=true;p.socOrigin="MANUAL";p.lastValidatedSoc=p.estimatedSoc;p.lastValidationAt=System.currentTimeMillis();profileStore.saveProfile(p);}maybeSuggestBridge(p);updateVisible();}).show();}
    private void maybeSuggestBridge(ProfileStore.Profile p){List<BridgeStore.Bridge> matches=new ArrayList<>();for(BridgeStore.Bridge br:bridgeStore.load())if(!br.archived&&(br.sourceId.equals(p.id)||br.batteryAId.equals(p.id)||br.batteryBId.equals(p.id)))matches.add(br);if(matches.isEmpty())return;BridgeStore.Bridge br=matches.get(0);new AlertDialog.Builder(this).setTitle("Bridge-Vorschlag").setMessage("Zu diesem Profil passt die gespeicherte Bridge:\n\n"+br.name+"\n"+bridgeDescription(br)).setNegativeButton("NEIN",null).setPositiveButton("AKTIVIEREN",(d,w)->{bridgeStore.activate(br.id);updateVisible();}).show();}

    private void choosePhoto(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_PHOTO);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null)return;if(req==REQ_PHOTO){Uri u=data.getData();if(u==null||pendingPhotoProfile==null)return;try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}if(!pendingPhotoProfile.photoUris.contains(u.toString()))pendingPhotoProfile.photoUris.add(u.toString());profileStore.saveProfile(pendingPhotoProfile);runOcr(u,pendingPhotoProfile);}else if(req==REQ_EXPORT){Uri u=data.getData();if(u!=null)try{OutputStream os=getContentResolver().openOutputStream(u);os.write(pendingExport.getBytes("UTF-8"));os.close();toast("Bericht gespeichert.");}catch(Exception e){toast("Export fehlgeschlagen: "+e.getMessage());}}}
    private void runOcr(Uri u,ProfileStore.Profile p){try{InputImage img=InputImage.fromFilePath(this,u);TextRecognizer r=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);r.process(img).addOnSuccessListener(t->{p.ocrText=t.getText();extractOcr(t.getText(),p);profileStore.saveProfile(p);toast("OCR übernommen. Profil bitte prüfen.");showTab(Tab.PROFILES);}).addOnFailureListener(e->toast("OCR fehlgeschlagen"));}catch(Exception e){toast("Bild konnte nicht gelesen werden.");}}
    private void extractOcr(String text,ProfileStore.Profile p){Matcher m=Pattern.compile("(?i)([0-9][0-9., ]{2,})\\s*mAh").matcher(text);if(m.find())p.capacityMah=dbl(clean(m.group(1)),p.capacityMah);Matcher wh=Pattern.compile("(?i)([0-9]+(?:[.,][0-9]+)?)\\s*Wh").matcher(text);if(wh.find()&&p.capacityMah>0){double e=dbl(clean(wh.group(1)),0);if(e>0)p.nominalV=e/(p.capacityMah/1000.0);}Matcher v=Pattern.compile("(?i)([0-9]+(?:[.,][0-9]+)?)\\s*V").matcher(text);if(v.find())p.profileMaxVoltage=dbl(clean(v.group(1)),p.profileMaxVoltage);Matcher a=Pattern.compile("(?i)([0-9]+(?:[.,][0-9]+)?)\\s*A").matcher(text);if(a.find())p.profileMaxCurrent=dbl(clean(a.group(1)),p.profileMaxCurrent);}
    private void testCable(ProfileStore.Profile p){long since=System.currentTimeMillis()-5*60*1000L;List<HistoryStore.Point> pts=HistoryStore.readSince(this,since,0);ArrayList<Double> vs=new ArrayList<>(),as=new ArrayList<>();for(HistoryStore.Point x:pts){if(!Double.isNaN(x.sourceV))vs.add(x.sourceV);if(!Double.isNaN(x.sourceA))as.add(Math.abs(x.sourceA));}if(vs.size()<5){new AlertDialog.Builder(this).setTitle("Kabeltest nicht vollständig möglich").setMessage("Dieses Android-Gerät liefert aktuell nicht genug direkte VBUS-Messwerte. Es wird keine erfundene Kabelqualität ausgegeben. Maximalleistung und E-Marker können weiterhin im Profil dokumentiert werden.").setPositiveButton("OK",null).show();return;}double min=Collections.min(vs),max=Collections.max(vs),avg=0;for(double x:vs)avg+=x;avg/=vs.size();double drop=max-min;double meanA=0;for(double x:as)meanA+=x;meanA=as.isEmpty()?0:meanA/as.size();double score=clamp(100-(drop/Math.max(.1,avg))*500,0,100);p.cableVoltageDrop=drop;p.cableQuality=score;p.cableResistanceOhm=meanA>.05?drop/meanA:Double.NaN;profileStore.saveProfile(p);new AlertDialog.Builder(this).setTitle("Kabeltest").setMessage("Stabilitäts-/Spannungsabfall-Score: "+fmt0(score)+"/100\nVBUS-Bereich: "+fmt3(min)+"–"+fmt3(max)+" V\nΔ: "+fmt3(drop)+" V"+(Double.isNaN(p.cableResistanceOhm)?"":"\n≈ "+fmt3(p.cableResistanceOhm)+" Ω")+"\n\nBewertung basiert ausschließlich auf den tatsächlich verfügbaren Messwerten.").setPositiveButton("OK",null).show();}

    private void exportReport(){try{JSONObject o=new JSONObject();o.put("app","CCOP LadeMonitor v9 LIVE INVENTORY");o.put("createdAt",System.currentTimeMillis());o.put("telemetry",telemetry);JSONArray ps=new JSONArray();for(ProfileStore.Profile p:profileStore.load())ps.put(p.toJson());o.put("profiles",ps);JSONArray bs=new JSONArray();for(BridgeStore.Bridge x:bridgeStore.load())bs.put(x.toJson());o.put("bridges",bs);o.put("historyCount",HistoryStore.count(this));o.put("noDemoDataPolicy",true);pendingExport=o.toString(2);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"ccop-lademonitor-report-"+new SimpleDateFormat("yyyyMMdd-HHmm",Locale.GERMANY).format(new Date())+".json");startActivityForResult(i,REQ_EXPORT);}catch(Exception e){toast("Bericht konnte nicht erstellt werden.");}}

    private Spinner profileSpinner(List<ProfileStore.Profile> list,String selected){Spinner s=new Spinner(this);ArrayList<String> n=new ArrayList<>();for(ProfileStore.Profile p:list)n.add(p.name);if(n.isEmpty())n.add("— nicht vorhanden —");s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,n));for(int i=0;i<list.size();i++)if(list.get(i).id.equals(selected))s.setSelection(i);return s;}
    private String idAt(List<ProfileStore.Profile> list,Spinner s){return list.isEmpty()?"":list.get(Math.min(s.getSelectedItemPosition(),list.size()-1)).id;}
    private String profileName(String id){ProfileStore.Profile p=profileStore.getById(id);return p==null?"—":p.name;}
    private String socLabel(ProfileStore.Profile p){return p.socKnown?fmt0(p.estimatedSoc)+"%":"unbekannt";}

    private void startMonitor(){Intent i=new Intent(this,TelemetryService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
    private boolean isPlugged(){return telemetry.optBoolean("plugged",false);}private boolean bool(String k){return telemetry.optBoolean(k,false);}private double val(String k){return telemetry.has(k)?telemetry.optDouble(k,Double.NaN):Double.NaN;}private String str(String k,String d){return telemetry.optString(k,d);}private boolean finite(double v){return !Double.isNaN(v)&&!Double.isInfinite(v);}private void set(String k,String s){TextView v=refs.get(k);if(v!=null)v.setText(s);}
    private String formatHours(double h){if(!finite(h)||h<=0)return"—";int hh=(int)h,mm=(int)Math.round((h-hh)*60);return hh+" h "+mm+" min";}private String formatRange(long ms){long m=ms/60000;if(m<60)return m+" min";double h=m/60.0;return h<24?fmt1(h)+" h":fmt1(h/24)+" Tage";}
    private String dateShort(long t){if(t<=0)return"noch nie";return new SimpleDateFormat("dd.MM. HH:mm",Locale.GERMANY).format(new Date(t));}
    private String clean(String s){return s.replace(" ","").replace(",",".");}private double dbl(String s,double d){try{return Double.parseDouble(clean(s));}catch(Exception e){return d;}}private double clamp(double v,double a,double b){return Math.max(a,Math.min(b,v));}private String nonEmpty(String s,String d){s=s==null?"":s.trim();return s.isEmpty()?d:s;}
    private String fmt0(double v){return String.format(Locale.GERMANY,"%.0f",v);}private String fmt1(double v){return String.format(Locale.GERMANY,"%.1f",v);}private String fmt2(double v){return String.format(Locale.GERMANY,"%.2f",v);}private String fmt3(double v){return String.format(Locale.GERMANY,"%.3f",v);}private String fmtNoGroup(double v){return String.format(Locale.US,"%.3f",v).replaceAll("0+$","").replaceAll("\\.$","");}
    private TextView txt(String s,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);if(bold)v.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private TextView label(String s){TextView v=txt(s,12,MUTED,true);v.setPadding(0,dp(8),0,dp(3));return v;}
    private EditText input(String s,String hint){EditText e=new EditText(this);e.setText(s);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(TEXT);e.setSingleLine(false);e.setPadding(dp(8),dp(10),dp(8),dp(10));return e;}
    private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);b.setBackground(round(BLUE,BLUE,22));b.setMinHeight(dp(66));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(CYAN);b.setBackground(round(PANEL,BLUE,16));b.setMinHeight(dp(54));return b;}private Button mini(String s){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(TEXT);b.setBackground(round(Color.rgb(13,32,45),LINE,12));return b;}
    private ProgressBar progress(){ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgressTintList(android.content.res.ColorStateList.valueOf(BLUE));p.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(21,35,44)));return p;}
    private GradientDrawable round(int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));g.setStroke(dp(1),stroke);return g;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
