package com.ccop.usbcpowermonitor;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import androidx.core.content.FileProvider;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.Text;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import org.json.JSONObject;
import java.io.*;
import java.util.*;
import java.util.regex.*;

/** Full-screen first-use / edit workflow. No opaque popup: every source value and OCR token is reviewable. */
public class SetupWizardActivity extends Activity {
    private static final int BG=Color.rgb(6,11,15),PANEL=Color.rgb(14,25,34),LINE=Color.rgb(43,61,74),TEXT=Color.rgb(247,249,252),MUTED=Color.rgb(151,164,178),BLUE=Color.rgb(24,153,255),CYAN=Color.rgb(73,194,255),OK=Color.rgb(48,214,132),WARN=Color.rgb(255,196,71);
    private static final int REQ_PICK=301,REQ_CAMERA=302,REQ_CABLE=303;
    private ProfileStore store; private BridgeStore bridges; private ProfileStore.Profile p; private JSONObject live=new JSONObject();
    private EditText name,mah,nomV,soc,maxV,maxA,eff,note,cableW,cableLen; private Spinner type,cableSpinner; private CheckBox pass,eMarker,bridgeCreate; private TextView auditTitle,bridgeSummary,photoCount;
    private LinearLayout auditRows; private OcrOverlayView overlay; private Bitmap lastBitmap; private Uri pendingCameraUri; private File pendingCameraFile; private String signature=""; private boolean firstUse=false;

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(4,21,30));getWindow().setNavigationBarColor(BG);store=new ProfileStore(this);bridges=new BridgeStore(this);String id=getIntent().getStringExtra("profileId");p=id==null?null:store.getById(id);if(p==null)p=new ProfileStore.Profile();firstUse=getIntent().getBooleanExtra("firstUse",false);loadLive();String force=getIntent().getStringExtra("forceType");if(force!=null&&!force.isEmpty())p.type=force;signature=live.optString("signature",p.connectionSignature);if(firstUse&&!signature.isEmpty()&&p.connectionSignature.isEmpty())p.connectionSignature=signature;setContentView(build());}

    private void loadLive(){try{SharedPreferences sp=getSharedPreferences(TelemetryServiceV10.PREFS,MODE_PRIVATE);String s=sp.getString(TelemetryServiceV10.KEY_LATEST,"");if(!s.isEmpty())live=new JSONObject(s);}catch(Exception ignored){}}
    private View build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(14),dp(18),dp(28));root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(dp(18),dp(14)+in.getSystemWindowInsetTop(),dp(18),dp(28)+in.getSystemWindowInsetBottom());return in;});scroll.addView(root);
        TextView title=txt(firstUse?"Erstverwendung · Gerät vollständig prüfen":"Geräteprofil · Vollprüfung",28,TEXT,true);root.addView(title);root.addView(txt("LIVE → FOTO/OCR → EINHEITEN → SOC → KABEL → BRIDGE → BESTÄTIGEN",11,CYAN,true));
        addCard(root,connectionCard());addCard(root,photoCard());addCard(root,deviceCard());addCard(root,cableCard());addCard(root,bridgeCard());
        Button save=primary("PRÜFUNG ABSCHLIESSEN & GERÄT BESTÄTIGEN");save.setOnClickListener(v->saveAll());addCard(root,save);Button cancel=secondary("ABBRECHEN");cancel.setOnClickListener(v->finish());addCard(root,cancel);return scroll;}

    private LinearLayout connectionCard(){LinearLayout c=card();c.addView(txt("1 · Live-Verbindung / Messquelle",18,TEXT,true));c.addView(txt("Diese Werte kommen aus Android bzw. OEM-Systempfaden. Sie werden nicht aus dem Foto abgeleitet.",11,MUTED,false));metric(c,"Status",live.optBoolean("plugged",false)?(live.optBoolean("charging",false)?"Laden aktiv":"Quelle verbunden"):"keine Quelle",live.optBoolean("plugged",false)?OK:MUTED);metric(c,"Signatur",live.optString("signature","—"),CYAN);metric(c,"Anschluss",live.optString("plugType","—"),TEXT);metric(c,"USB/OEM Typ",live.optString("sourceType","—"),TEXT);metric(c,"MAX-Profil",fmtOpt("profileMaxV","V")+" / "+fmtOpt("profileMaxA","A"),TEXT);metric(c,"VBUS LIVE",fmtOpt("sourceV","V")+pathSuffix("sourceVPath"),finite(live,"sourceV")?OK:WARN);metric(c,"IBUS LIVE",fmtOpt("sourceA","A")+pathSuffix("sourceAPath"),finite(live,"sourceA")?OK:WARN);metric(c,"Smartphone",fmtOpt("phonePct","%")+" · "+fmtOpt("batteryW","W netto"),TEXT);return c;}

    private LinearLayout photoCard(){LinearLayout c=card();c.addView(txt("2 · Foto & OCR · Bild für Bild prüfbar",18,TEXT,true));c.addView(txt("Tippe unten auf jede OCR-Zeile bzw. jedes OCR-Element: die zugehörige Stelle wird im Bild markiert.",11,MUTED,false));overlay=new OcrOverlayView(this);c.addView(overlay,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(260)));photoCount=txt(p.photoUris.size()+" gespeicherte Bilder",11,MUTED,false);c.addView(photoCount);LinearLayout row=new LinearLayout(this);Button cam=secondary("FOTO AUFNEHMEN");cam.setOnClickListener(v->capture());Button pick=secondary("BILD WÄHLEN");pick.setOnClickListener(v->pick());row.addView(cam,new LinearLayout.LayoutParams(0,dp(56),1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(56),1);rp.setMargins(dp(8),0,0,0);row.addView(pick,rp);c.addView(row);auditTitle=txt("OCR-Prüftabelle · noch kein neues Bild analysiert",13,CYAN,true);auditTitle.setPadding(0,dp(10),0,dp(6));c.addView(auditTitle);HorizontalScrollView hs=new HorizontalScrollView(this);auditRows=new LinearLayout(this);auditRows.setOrientation(LinearLayout.VERTICAL);hs.addView(auditRows,new HorizontalScrollView.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT));c.addView(hs,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(230)));if(!p.photoUris.isEmpty()){try{Uri u=Uri.parse(p.photoUris.get(p.photoUris.size()-1));Bitmap bm=MediaStore.Images.Media.getBitmap(getContentResolver(),u);overlay.setData(bm,new ArrayList<>());}catch(Exception ignored){}}return c;}

    private LinearLayout deviceCard(){LinearLayout c=card();c.addView(txt("3 · Gerätedaten · Einheit für Einheit bestätigen",18,TEXT,true));String[] types={"POWERBANK","EXTERNAL_BATTERY","CHARGER","CABLE"};type=new Spinner(this);type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,types));type.setSelection(Math.max(0,Arrays.asList(types).indexOf(p.type)));addField(c,"Typ",type);name=input(p.name.equals("Neues Gerät")?"":p.name,"Hersteller / Modell");mah=input(p.capacityMah>0?n(p.capacityMah):"","Kapazität mAh");nomV=input(p.nominalV>0?n(p.nominalV):"","Nennspannung V");soc=input(p.socKnown?n(p.estimatedSoc):"","Akkustand % · manuell am Gerät ablesen");maxV=input(p.profileMaxVoltage>0?n(p.profileMaxVoltage):"","Max. Spannung V");maxA=input(p.profileMaxCurrent>0?n(p.profileMaxCurrent):"","Max. Strom A");eff=input(n(p.efficiency*100),"Wirkungsgrad %");note=input(p.note,"Notiz / Serieninfo / Besonderheiten");addField(c,"Modell",name);addField(c,"Kapazität",mah);addField(c,"Nennspannung",nomV);addField(c,"SOC / Bestand",soc);addField(c,"Max. V",maxV);addField(c,"Max. A",maxA);addField(c,"Wirkungsgrad",eff);pass=new CheckBox(this);pass.setText("Pass-through unterstützt");pass.setTextColor(TEXT);pass.setChecked(p.passthrough);c.addView(pass);addField(c,"Notiz",note);metric(c,"Hash",p.deviceHash,TEXT);metric(c,"Messsignatur",p.connectionSignature.isEmpty()?"wird nach Bestätigung gesetzt":p.connectionSignature,CYAN);return c;}

    private LinearLayout cableCard(){LinearLayout c=card();c.addView(txt("4 · Kabel / Verbindungsweg",18,TEXT,true));c.addView(txt("Ein Kabel ist ein eigenes Inventarobjekt. Live-Qualität wird nur berechnet, wenn VBUS/IBUS tatsächlich messbar sind.",11,MUTED,false));List<ProfileStore.Profile> cables=cables();ArrayList<String> labels=new ArrayList<>();labels.add("— kein Kabelprofil / später —");for(ProfileStore.Profile q:cables)labels.add(q.name+(Double.isNaN(q.cableQuality)?"":" · Q "+String.format(Locale.GERMANY,"%.0f",q.cableQuality)+"/100"));cableSpinner=new Spinner(this);cableSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));String active=store.getActiveCableId();for(int i=0;i<cables.size();i++)if(cables.get(i).id.equals(active))cableSpinner.setSelection(i+1);addField(c,"Aktives Kabel",cableSpinner);Button newCable=secondary("KABEL PER FOTO / OCR ERFASSEN");newCable.setOnClickListener(v->{Intent i=new Intent(this,SetupWizardActivity.class);i.putExtra("forceType","CABLE");startActivityForResult(i,REQ_CABLE);});c.addView(newCable);cableW=input(p.cableMaxW>0?n(p.cableMaxW):"","nur bei Kabel: max. W");cableLen=input(p.cableLengthM>0?n(p.cableLengthM):"","nur bei Kabel: Länge m");eMarker=new CheckBox(this);eMarker.setText("E-Marker vorhanden");eMarker.setTextColor(TEXT);eMarker.setChecked(p.cableEMarked);addField(c,"Kabel max. W",cableW);addField(c,"Kabellänge",cableLen);c.addView(eMarker);return c;}

    private LinearLayout bridgeCard(){LinearLayout c=card();c.addView(txt("5 · Bridge-Vorschlag",18,TEXT,true));ProfileStore.Profile other=bestOtherBattery();ProfileStore.Profile cab=activeCable();String s;if(!p.isEnergyStore())s="Dieses Profil ist kein Akku/Powerbank-Profil. Eine Akku-Bridge wird nicht vorgeschlagen.";else if(other==null)s="Noch kein zweiter bestätigter Akku vorhanden. Nach dem Anlegen eines weiteren Akkus wird automatisch neu vorgeschlagen.";else s="Vorschlag: "+p.name+" + "+other.name+" · Kabel: "+(cab==null?"noch offen":cab.name)+" · Modus: POOL\nGesamtenergie wird nur aus bekannten Kapazitäten und bestätigten SOCs berechnet.";bridgeSummary=txt(s,13,MUTED,false);c.addView(bridgeSummary);bridgeCreate=new CheckBox(this);bridgeCreate.setText("Bridge nach Bestätigung als Vorschlag anlegen und aktivieren");bridgeCreate.setTextColor(TEXT);bridgeCreate.setChecked(p.isEnergyStore()&&other!=null);bridgeCreate.setEnabled(p.isEnergyStore()&&other!=null);c.addView(bridgeCreate);return c;}

    private void saveAll(){p.name=nonEmpty(name.getText().toString(),"Unbenanntes Gerät");p.type=String.valueOf(type.getSelectedItem());p.capacityMah=dbl(mah.getText().toString());p.nominalV=dbl(nomV.getText().toString());String ss=soc.getText().toString().trim();if(ss.isEmpty()){p.socKnown=false;p.estimatedSoc=Double.NaN;p.socOrigin="UNBEKANNT";}else{p.estimatedSoc=clamp(dbl(ss),0,100);p.socKnown=true;p.socOrigin="MANUAL";p.lastValidatedSoc=p.estimatedSoc;p.lastValidationAt=System.currentTimeMillis();}p.profileMaxVoltage=dbl(maxV.getText().toString());p.profileMaxCurrent=dbl(maxA.getText().toString());p.efficiency=clamp(dblDefault(eff.getText().toString(),88)/100.0,.5,1);p.passthrough=pass.isChecked();p.note=note.getText().toString();p.cableMaxW=dbl(cableW.getText().toString());p.cableLengthM=dbl(cableLen.getText().toString());p.cableEMarked=eMarker.isChecked();p.lastSeenAt=System.currentTimeMillis();if(!signature.isEmpty())p.connectionSignature=signature;p.autoConfigured=firstUse;store.saveProfile(p);if(!p.isCable())store.setActiveId(p.id);else store.setActiveCableId(p.id);List<ProfileStore.Profile> cs=cables();int ci=cableSpinner.getSelectedItemPosition()-1;if(ci>=0&&ci<cs.size())store.setActiveCableId(cs.get(ci).id);if(bridgeCreate.isChecked())createSuggestedBridge();setResult(RESULT_OK,new Intent().putExtra("profileId",p.id));finish();}
    private void createSuggestedBridge(){ProfileStore.Profile other=bestOtherBattery();if(other==null)return;BridgeStore.Bridge b=new BridgeStore.Bridge();b.name="Auto · "+shortName(p.name)+" + "+shortName(other.name);b.batteryAId=p.id;b.batteryBId=other.id;b.sourceId=p.id;ProfileStore.Profile cab=activeCable();b.cableId=cab==null?"":cab.id;b.mode="POOL";bridges.save(b);bridges.activate(b.id);}

    private void capture(){try{File dir=new File(getExternalFilesDir(Environment.DIRECTORY_PICTURES),"device-labels");dir.mkdirs();pendingCameraFile=new File(dir,"ccop_"+System.currentTimeMillis()+".jpg");pendingCameraUri=FileProvider.getUriForFile(this,getPackageName()+".files",pendingCameraFile);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,pendingCameraUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,REQ_CAMERA);}catch(Exception e){toast("Kamera konnte nicht gestartet werden: "+e.getMessage());}}
    private void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_PICK);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==REQ_CABLE){refreshCableSpinner();return;}if(res!=RESULT_OK)return;Uri u=req==REQ_CAMERA?pendingCameraUri:(data==null?null:data.getData());if(u==null)return;if(req==REQ_PICK)try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}if(!p.photoUris.contains(u.toString()))p.photoUris.add(u.toString());store.saveProfile(p);photoCount.setText(p.photoUris.size()+" gespeicherte Bilder");runOcr(u);}
    private void runOcr(Uri u){try{lastBitmap=MediaStore.Images.Media.getBitmap(getContentResolver(),u);InputImage image=InputImage.fromFilePath(this,u);TextRecognizer r=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);r.process(image).addOnSuccessListener(t->{p.ocrText=t.getText();store.saveProfile(p);showOcr(t);applyCandidates(t.getText());}).addOnFailureListener(e->toast("OCR fehlgeschlagen: "+e.getMessage()));}catch(Exception e){toast("Bild konnte nicht analysiert werden.");}}
    private void showOcr(Text t){auditRows.removeAllViews();ArrayList<OcrOverlayView.Item> items=new ArrayList<>();int lineNo=0,index=0;for(Text.TextBlock b:t.getTextBlocks())for(Text.Line l:b.getLines()){lineNo++;int elNo=0;for(Text.Element e:l.getElements()){elNo++;String id="Z"+lineNo+"."+elNo;items.add(new OcrOverlayView.Item(e.getBoundingBox(),e.getText(),id));final int ix=index++;TextView row=txt(String.format(Locale.GERMANY,"%-6s  %-10s  %s",id,unit(e.getText()),e.getText()),12,TEXT,false);row.setPadding(dp(6),dp(7),dp(10),dp(7));row.setBackgroundColor(lineNo%2==0?Color.rgb(13,24,33):Color.rgb(9,18,25));row.setOnClickListener(v->overlay.select(ix));auditRows.addView(row,new LinearLayout.LayoutParams(dp(760),ViewGroup.LayoutParams.WRAP_CONTENT));}}overlay.setData(lastBitmap,items);auditTitle.setText(items.size()+" OCR-Elemente · antippen = im Bild markieren");}
    private void applyCandidates(String text){Matcher m=Pattern.compile("(?i)([0-9][0-9., ]{2,})\\s*mAh").matcher(text);if(m.find()&&mah.getText().toString().trim().isEmpty())mah.setText(clean(m.group(1)));Matcher wh=Pattern.compile("(?i)([0-9]+(?:[.,][0-9]+)?)\\s*Wh").matcher(text);Double whVal=null;if(wh.find())whVal=dbl(clean(wh.group(1)));Matcher vv=Pattern.compile("(?i)([0-9]+(?:[.,][0-9]+)?)\\s*V").matcher(text);if(vv.find()&&maxV.getText().toString().trim().isEmpty())maxV.setText(clean(vv.group(1)));Matcher aa=Pattern.compile("(?i)([0-9]+(?:[.,][0-9]+)?)\\s*A").matcher(text);if(aa.find()&&maxA.getText().toString().trim().isEmpty())maxA.setText(clean(aa.group(1)));double cm=dbl(mah.getText().toString());if(nomV.getText().toString().trim().isEmpty()&&whVal!=null&&cm>0)nomV.setText(n(whVal/(cm/1000.0)));if(name.getText().toString().trim().isEmpty()){for(String ln:text.split("\\n")){String z=ln.trim();String low=z.toLowerCase(Locale.ROOT);if(z.length()>=5&&z.length()<=60&&z.matches(".*[A-Za-z].*")&&!low.contains("capacity")&&!low.contains("input")&&!low.contains("output")&&!low.contains("warning")&&!low.contains("made in")){name.setText(z);break;}}}}

    private void refreshCableSpinner(){if(cableSpinner==null)return;List<ProfileStore.Profile> cs=cables();ArrayList<String> ls=new ArrayList<>();ls.add("— kein Kabelprofil / später —");for(ProfileStore.Profile q:cs)ls.add(q.name);cableSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ls));}
    private List<ProfileStore.Profile> cables(){ArrayList<ProfileStore.Profile> out=new ArrayList<>();for(ProfileStore.Profile q:store.loadActiveInventory())if(q.isCable())out.add(q);return out;}private ProfileStore.Profile activeCable(){return store.getActiveCable();}
    private ProfileStore.Profile bestOtherBattery(){ProfileStore.Profile best=null;for(ProfileStore.Profile q:store.loadActiveInventory())if(q.isEnergyStore()&&!q.id.equals(p.id)){if(best==null||((q.socKnown?1:0)>(best.socKnown?1:0)))best=q;}return best;}
    private String shortName(String s){return s.length()>18?s.substring(0,18):s;}private String unit(String s){String x=s.toLowerCase(Locale.ROOT);if(x.contains("mah"))return"mAh";if(x.contains("wh"))return"Wh";if(x.matches(".*\\d\\s*v.*"))return"V";if(x.matches(".*\\d\\s*a.*"))return"A";if(x.contains("%"))return"%";if(x.matches(".*\\d\\s*w.*"))return"W";return"TEXT";}
    private String fmtOpt(String k,String u){return finite(live,k)?String.format(Locale.GERMANY,"%.3f %s",live.optDouble(k),u):"nicht verfügbar";}private boolean finite(JSONObject j,String k){double v=j.optDouble(k,Double.NaN);return !Double.isNaN(v)&&!Double.isInfinite(v);}private String pathSuffix(String k){String s=live.optString(k,"");return s.isEmpty()?"":"\n"+s;}
    private void metric(LinearLayout c,String l,String v,int color){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.TOP);TextView a=txt(l,12,MUTED,false),b=txt(v,12,color,true);b.setGravity(Gravity.END);r.addView(a,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,.34f));r.addView(b,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,.66f));c.addView(r);}
    private void addField(LinearLayout c,String label,View v){TextView l=txt(label,11,MUTED,true);l.setPadding(0,dp(8),0,dp(2));c.addView(l);c.addView(v,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(round(PANEL,LINE,18));return c;}private void addCard(LinearLayout b,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.setMargins(0,0,0,dp(12));b.addView(v,p);}private TextView txt(String s,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private EditText input(String s,String hint){EditText e=new EditText(this);e.setText(s);e.setHint(hint);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine(false);return e;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(round(BLUE,BLUE,18));b.setMinHeight(dp(64));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(CYAN);b.setBackground(round(PANEL,BLUE,15));b.setMinHeight(dp(54));return b;}private GradientDrawable round(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private double dbl(String s){try{return Double.parseDouble(clean(s));}catch(Exception e){return 0;}}private double dblDefault(String s,double d){try{return Double.parseDouble(clean(s));}catch(Exception e){return d;}}private String clean(String s){return s==null?"":s.replace(" ","").replace(",",".");}private String n(double v){return String.format(Locale.US,"%.3f",v).replaceAll("0+$","").replaceAll("\\.$","");}private double clamp(double v,double a,double b){return Math.max(a,Math.min(b,v));}private String nonEmpty(String s,String d){s=s==null?"":s.trim();return s.isEmpty()?d:s;}
}
